<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
		<UseWPF>true</UseWPF>
		<RootNamespace>YMM4_shape_fusion_plugin</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyName>shape-fusion-plugin</AssemblyName>
		<LangVersion>latest</LangVersion>
		<YMM4DirPath>W:\yt_job\main_program\YMM4_Lite\</YMM4DirPath>
		<Version>0.1.0</Version>
		<Authors>kikaisya-tdd</Authors>
		<Product>図形融合したいプラグイン</Product>
		<Description>図形を融合できるようにしたいプラグイン｡現在は円形のみ｡</Description>
		<NeutralLanguage>ja-JP</NeutralLanguage>
	</PropertyGroup>
	<ItemGroup>
		<Reference Include="YukkuriMovieMaker.Controls">
			<HintPath>$(YMM4DirPath)YukkuriMovieMaker.Controls.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="YukkuriMovieMaker.Plugin">
			<HintPath>$(YMM4DirPath)YukkuriMovieMaker.Plugin.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="SharpGen.Runtime">
			<HintPath>$(YMM4DirPath)SharpGen.Runtime.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="SharpGen.Runtime.COM">
			<HintPath>$(YMM4DirPath)SharpGen.Runtime.COM.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Vortice.Direct2D1">
			<HintPath>$(YMM4DirPath)Vortice.Direct2D1.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Vortice.DirectX">
			<HintPath>$(YMM4DirPath)Vortice.DirectX.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Vortice.Mathematics">
			<HintPath>$(YMM4DirPath)Vortice.Mathematics.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>
	<Target Name="PostBuild" AfterTargets="Build" Condition="'$(SkipPluginCopy)' != 'true'">
		<MakeDir Directories="$(YMM4DirPath)user\plugin\$(AssemblyName)" />
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(YMM4DirPath)user\plugin\$(AssemblyName)" SkipUnchangedFiles="true" />
	</Target>
</Project>
